openapi: 3.0.0
info:
  title: Node.js + MongoDB API - BookStore
  version: 1.0.0

servers:
  - url: http://localhost:8001
    description: Local development server
    
paths:
  /auth/login:
    post:
      summary: Authentication API for Login which return token upon success
      operationId: authenticate
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'abc@email.com'
                password:
                  type: string
                  example: '12456'
      responses:
        "200": 
          description: Login user to get authentication JWT token
          content:
            application/json:
              schema: 
                type: object
                $ref: "#/definitions/Response"

definitions:
  Response:
    type: object
    properties:
      status: 
        type: string
        example: "200"
      code:
        type: string
        example: 'SUCCESS'
      message:
        type: string
        example: ''
      data: 
        $ref: "#/definitions/User"
  User:
    type: object
    properties:
      role:
        type: string
        example: 'USER'
                  
                  
              
            