
module.exports = {
  // GENERAL
  OTHER_ERROR: "OTHER_ERROR",
  API_SUCCESS: "API_SUCCESS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ERROR_SCAN_FILES: "ERROR_SCAN_FILES",
  // AUTHENTICATE
  PERMISSION: "PERMISSION",
  UNAUTHORIZED: "UNAUTHORIZED",
  // LOGIN REGISTER
  LOGIN_FAIL: "LOGIN_FAIL",
  EMAIL_EXISTED: "EMAIL_EXISTED",
  USER_NOT_EXIST: "USER_NOT_EXIST",
  USER_EXIST: "USER_EXIST",
  // IMAGE UPLOAD
  UPLOAD_FILE_EXTENSION: "UPLOAD_FILE_EXTENSION",
  NO_UPLOAD_FILE: "NO_UPLOAD_FILE",
  UPLOAD_FILE_LIMIT: "UPLOAD_FILE_LIMIT",
  // BOOK
  BOOK_TITLE_EXISTED: "BOOK_TITLE_EXISTED",
  BOOK_NOT_EXISTED: "BOOK_NOT_EXISTED",
};
